name: Terraform Apply
on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
permissions:
  id-token: write  # Required for OID
  contents: read
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539935451710:role/github_oidc
          aws-region: us-east-1
          role-session-name: GitHubActions-Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -input=false
        env:
          TF_VAR_environment: prod